- name: install packages
  apt: name={{item}} state=latest
  with_items:
    - postgresql-9.4
    - python-psycopg2

- name: create PostgreSQL user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=cs password=jrCiW2c9268x state=present

- name: create test PostgreSQL database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cs_test owner=cs state=present

- name: create production PostgreSQL database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=cs_prod owner=cs state=present

- name: copy pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  notify: restart postgresql

- name: copy postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.4/main/postgresql.conf
  notify: restart postgresql

