- apt: name=nginx state=latest

- copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: create dir for nginx images
  file: path=/var/nginx/images state=directory recurse=yes owner=cs group=www-data mode="u=rwx,g=rx"

- name: upload upstart scripts
  template: src={{item}} dest=/etc/init/
  with_items:
    - cs-flags.conf
    - cs-watcher.conf
    - cs-manager.conf
    - cs-web.conf
    - cs-worker-default.conf
