net_dev_vpn       : 10.8.0.0/24         # Developers VPN (runs on g1)
net_teams_int     : 10.60.0.0/15        # All teams internal networks
net_teams_vpn     : 10.80.0.0/15        # All teams tun networks
net_jury          : 10.10.10.0/24       # Jury network (same in both datacenters)
net_g             : 10.10.11.0/24       # Datacenter G unique network
net_h             : 10.10.12.0/24       # Datacenter H unique network
net_tun_gh        : 172.16.16.0/24      # Tun network between DC G and DC H
net_vms_g1        : 10.70.0.0/24        # Network for dev VMs at g1
net_vms_g7        : 10.70.1.0/24        # Network for dev VMs at g7
net_vms_h7        : 10.70.2.0/24        # Network for dev VMs at h7
net_vms           : 10.70.0.0/16        # All VMs
