- name: upload upstart scripts
  template: src={{item}} dest=/etc/init/
  with_items:
    - cs-worker-checker.conf

- name: upload checkers
  synchronize: src=../../../../../../checkers/ dest={{cs_dir}}/checkers

- name: chown checkers
  file: path={{cs_dir}}/checkers owner={{cs_user}} group={{cs_user}} recurse=yes

#################################### Checkers requirements ###################################

- name: checker requirements - MoL - python3
  apt: name={{item}} state=present
  with_items:
    - python3
    - python3-setuptools
    - unicode

- name: checker requirements - MoL - pip
  easy_install: executable=easy_install3 name={{item}}
  with_items:
    - pip

- name: checker requirements - MoL - websocket-client
  pip: executable=pip3 name=websocket-client state=present

# commented, because it fails when package is already uninstalled
#- name: checker requirements - MoL - remove websocket
#  pip: executable=pip3 name=websocket state=absent
#  ignore_errors: yes

- name: checker requirements - TaX
  apt: name={{item}} state=latest
  with_items:
    - libwww-perl

- name: checker requirements - Electro - apt key
  apt_key: keyserver=keyserver.ubuntu.com id=3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: checker requirements - Electro - apt repository
  apt_repository: repo="{{item}}" state=present
  notify: update apt
  with_items:
    - "deb http://download.mono-project.com/repo/debian wheezy main"
    - "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main"

- name: checker requirements - Electro - mono
  apt: name=mono-devel state=latest

- name: checker requirements - Nasarasa - requests
  pip: executable=pip3 name={{item}} state=latest
  with_items:
    - requests
    - enum34

################################ End of checkers requirements ################################


