- name: stop checkers
  service: name={{item}} state=stopped
  when: mode=="stop"
  with_items:
    - cs-worker-checker

- name: start checkers
  service: name={{item}} state=started
  when: mode=="start"
  with_items:
    - cs-worker-checker
