- hosts: all
  roles: [common]

- hosts: router
  roles: [router]

- hosts: dns
  roles: [dns]

- hosts: checksystem-main:checksystem-checkers
  roles: [checksystem-app]

- hosts: checksystem-db
  roles: [checksystem-db]
  gather_facts: yes
