- hosts: all
  roles: [common]

- hosts: router
  roles: [router]

- hosts: dns
  roles: [dns]

- hosts: checksystem-app
  roles: [checksystem-app]

- hosts: checksystem-db
  roles: [checksystem-db]

