- name: install packages
  apt: name={{item}} state=latest
  with_items:
    - libssl-dev
    - libpq-dev
    - cpanminus
    - git

- name: create checksystem user
  user: name=checksystem state=present

- name: cpanm installdeps
  cpanm: name={{item}}
  with_items:
    - Convert::Color
    - EV
    - IO::Socket::SSL
    - IO::Socket::IP
    - IPC::Run
    - List::Util~1.42
    - String::Random
    - Mojolicious
    - Mojolicious::Plugin::Model
    - DBI
    - DBD::Pg
    - Mojo::Pg
    - Minion

