- name: Install packages
  apt: name={{item}} state=latest
  with_items:
    - libssl-dev
    - libpq-dev
    - cpanminus
    - git

- name: Create checksystem user
  user: name=checksystem state=present

