- name: copy apt sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: add PostgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: add ubuntu extras apt key
  apt_key: keyserver=keyserver.ubuntu.com id=16126D3A3E5C1192 state=present

- name: add virtualbox apt key
  apt_key: keyserver=keyserver.ubuntu.com id=54422A4B98AB5139 state=present

- name: add nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: update apt cache
  apt: update_cache=yes cache_valid_time=79800

- name: copy aliases
  template: src=aliases.j2 dest=/etc/aliases

- name: apply aliases
  shell: newaliases

- name: install common network packages
  apt: name={{item}} state=latest
  with_items:
    - conntrack
    - iptables
    - iptables-persistent
    - telnet
    - tcpdump
    - tcpflow
    - iperf
    - cpu-checker

- name: copy sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh

- name: set default locale
  template: src=locale.j2 dest=/etc/default/locale

